/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Oracle;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYEN THI KIM DUNG
 */
public class Grant extends javax.swing.JFrame {

    /**
     * Creates new form Grant
     */
    private String header[] = {"Username"};
    private DefaultTableModel tblModel ;
    private Vector vctData = new Vector();
    private String username;
    private String password;
    private String dbURL = "jdbc:oracle:thin:@localhost:1521:orcl";
    public Grant(String username,String password) {
        initComponents();
        this.username=username;
        if(username.equals("sys"))
                this.username = "sys as sysdba";
        this.password=password;
        this.setLocationRelativeTo(null);
    }

    private Grant() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonCapQuyen = new javax.swing.JButton();
        ButtonThuHoiQuyen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ButtonLoadGr = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ButtonCreateGroupGrant = new javax.swing.JButton();
        ButtonDeleteGroupGrant = new javax.swing.JButton();
        ButtonReturnMain = new javax.swing.JButton();
        ButtonGroupGrantUser = new javax.swing.JButton();
        ButtonThuHoiNhomQuyen = new javax.swing.JButton();
        GanQuyenChoNhom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grant"));

        jCheckBox1.setText("Select");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Update");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });

        jCheckBox3.setText("Insert");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });

        jCheckBox4.setText("Delete");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jLabel4))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "User"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        ButtonCapQuyen.setText("Cấp quyền");
        ButtonCapQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCapQuyenActionPerformed(evt);
            }
        });

        ButtonThuHoiQuyen.setText("Thu hồi quyền");
        ButtonThuHoiQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThuHoiQuyenActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhóm quyền"));

        jLabel5.setText("Tên nhóm");

        jLabel6.setText("Pass (nếu có)");

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel7.setText("Các nhóm quyền");

        ButtonLoadGr.setText("Load");
        ButtonLoadGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoadGrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonLoadGr)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 49, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 101, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1))
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLoadGr)
                    .addComponent(jLabel8)))
        );

        ButtonCreateGroupGrant.setText("Tạo nhóm");
        ButtonCreateGroupGrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateGroupGrantActionPerformed(evt);
            }
        });

        ButtonDeleteGroupGrant.setText("Xóa nhóm");
        ButtonDeleteGroupGrant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteGroupGrantActionPerformed(evt);
            }
        });

        ButtonReturnMain.setText("Quay lại Main");
        ButtonReturnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReturnMainActionPerformed(evt);
            }
        });

        ButtonGroupGrantUser.setText("Cấp role cho user");
        ButtonGroupGrantUser.setActionCommand("Cấp nhóm quyền");
        ButtonGroupGrantUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGroupGrantUserActionPerformed(evt);
            }
        });

        ButtonThuHoiNhomQuyen.setText("Thu hồi role của user");
        ButtonThuHoiNhomQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonThuHoiNhomQuyenActionPerformed(evt);
            }
        });

        GanQuyenChoNhom.setText("Cấp");
        GanQuyenChoNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GanQuyenChoNhomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonReturnMain)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonCapQuyen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonThuHoiQuyen))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonGroupGrantUser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonThuHoiNhomQuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonCreateGroupGrant)
                        .addGap(18, 18, 18)
                        .addComponent(GanQuyenChoNhom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDeleteGroupGrant, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCapQuyen)
                    .addComponent(ButtonThuHoiQuyen)
                    .addComponent(ButtonGroupGrantUser)
                    .addComponent(ButtonCreateGroupGrant)
                    .addComponent(ButtonDeleteGroupGrant)
                    .addComponent(ButtonThuHoiNhomQuyen)
                    .addComponent(GanQuyenChoNhom))
                .addGap(31, 31, 31)
                .addComponent(ButtonReturnMain)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // khởi động form
        try{
            tblModel = new DefaultTableModel(header, 0);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select username from dba_users where account_status = 'OPEN' and default_tablespace = 'USERS'" );
            
            Vector data = null;
            tblModel.setRowCount(0); 
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Chưa có thông tin!");
                return;
            }
 
            while (rs.next()) {
            data = new Vector();
            // Dữ liệu cột 1
            data.add(rs.getString("username"));
            // Thêm một dòng vào table model
            tblModel.addRow(data);
        }
        // Hiển thị dữ liệu lên table
            jTable1.setModel(tblModel);
            
            con.close();
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select table_name from dba_tables where OWNER='"+username+"'" );
            while (rs.next()) {
            // Dữ liệu cột 1
            jComboBox1.addItem(rs.getString("table_name"));
            }
            con.close();
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowActivated

    private void ButtonCapQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCapQuyenActionPerformed
        // cấp quyền
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
//                    "jdbc:oracle:thin:@localhost:1521:orcl", "sys as sysdba", "Matkhau123");
            int vt= jTable1.getSelectedRow();
            String nameTable = jComboBox1.getSelectedItem().toString();
            String grt1 = jLabel1.getText();
            String grt2 = jLabel2.getText();
            String grt3 = jLabel3.getText();
            String grt4 = jLabel4.getText();
            String user_name = jTable1.getValueAt(vt,0).toString();
            Statement stmt = con.createStatement();
            String lenh = "";
            int rs = 0;
            if(jLabel1.getText().equals("")==false){
                lenh = " grant "+grt1+" on "+nameTable+" to "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel2.getText().equals("")==false){
                lenh = " grant "+grt2+" on "+nameTable+" to "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel3.getText().equals("")==false){
                lenh = " grant "+grt3+" on "+nameTable+" to "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel4.getText().equals("")==false){
                lenh = " grant "+grt4+" on "+nameTable+" to "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Gán quyền thành công!");
                
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonCapQuyenActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // bat su kien checkbox
        if(evt.getStateChange()== ItemEvent.SELECTED){
            jLabel1.setText(jCheckBox1.getText());
        }
        else
            jLabel1.setText("");
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED)
            jLabel2.setText(jCheckBox2.getText());
        else
            jLabel2.setText("");
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED)
            jLabel3.setText(jCheckBox3.getText());
        else
            jLabel3.setText("");
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED)
            jLabel4.setText(jCheckBox4.getText());
        else
            jLabel4.setText("");
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void ButtonThuHoiQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThuHoiQuyenActionPerformed
        // Thu hoi quyen
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
//                    "jdbc:oracle:thin:@localhost:1521:orcl", "sys as sysdba", "Matkhau123");
            int vt= jTable1.getSelectedRow();
            String nameTable = jComboBox1.getSelectedItem().toString();
            String grt1 = jLabel1.getText();
            String grt2 = jLabel2.getText();
            String grt3 = jLabel3.getText();
            String grt4 = jLabel4.getText();
            String user_name = jTable1.getValueAt(vt,0).toString();
            Statement stmt = con.createStatement();
            String lenh = "";
            int rs = 1;
            if(jLabel1.getText().equals("")==false){
                lenh = " revoke "+grt1+" on "+nameTable+" from "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel2.getText().equals("")==false){
                lenh = " revoke "+grt2+" on "+nameTable+" from "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel3.getText().equals("")==false){
                lenh = " revoke "+grt3+" on "+nameTable+" from "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel4.getText().equals("")==false){
                lenh = " revoke "+grt4+" on "+nameTable+" from "+user_name;
                rs = stmt.executeUpdate(lenh);
            }
            
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Thu hồi quyền thành công!");
                
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonThuHoiQuyenActionPerformed

    private void ButtonCreateGroupGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateGroupGrantActionPerformed
        // Tạo nhóm quyền
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
            String namegr= jTextField1.getText();
            String pass = jTextField2.getText();
            Statement stmt = con.createStatement();
            int rs = 1;
            if(pass.equals(""))
            {
                rs = stmt.executeUpdate("create role "+namegr);
            }
            else{
                rs = stmt.executeUpdate("create role "+namegr+ " identified by "+pass);
            }
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Tạo role thành công!");
            con.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonCreateGroupGrantActionPerformed

    private void ButtonGroupGrantUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGroupGrantUserActionPerformed
        // cấp role cho user
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
//                    "jdbc:oracle:thin:@localhost:1521:orcl", "sys as sysdba", "Matkhau123");
            int vt= jTable1.getSelectedRow();
            String user_name = jTable1.getValueAt(vt,0).toString();
            String tenGr = jLabel8.getText();
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate("grant "+tenGr+" to "+user_name);
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Gán nhóm quyền cho user thành công!");
                
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonGroupGrantUserActionPerformed

    private void ButtonDeleteGroupGrantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteGroupGrantActionPerformed
        //xóa role
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
            String namegr= jLabel8.getText();
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate("drop role "+namegr);
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Xóa role thành công!");
            con.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonDeleteGroupGrantActionPerformed

    private void ButtonLoadGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoadGrActionPerformed
        // load các nhóm quyền
        try{
            jComboBox2.removeAllItems();
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select role from dba_roles where oracle_maintained = 'N'" );
            while (rs.next()) {
            // Dữ liệu cột 1
            jComboBox2.addItem(rs.getString("role"));
            
            }
            con.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonLoadGrActionPerformed

    private void ButtonReturnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReturnMainActionPerformed
        // quay lại main
        this.setVisible(false);
        
        if(username.equals("sys as sysdba"))
            username="sys";
        Main m = new Main(username,password);
        m.setVisible(true);
    }//GEN-LAST:event_ButtonReturnMainActionPerformed

    private void GanQuyenChoNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GanQuyenChoNhomActionPerformed
        // gán quyền cho role
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
//                    "jdbc:oracle:thin:@localhost:1521:orcl", "sys as sysdba", "Matkhau123");
            String nameTable = jComboBox1.getSelectedItem().toString();
            String grt1 = jLabel1.getText();
            String grt2 = jLabel2.getText();
            String grt3 = jLabel3.getText();
            String grt4 = jLabel4.getText();
            String gr_name = jTextField1.getText();
            Statement stmt = con.createStatement();
            String lenh = "";
            int rs = 0;
            if(jLabel1.getText().equals("")==false){
                lenh = " grant "+grt1+" on "+nameTable+" to "+gr_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel2.getText().equals("")==false){
                lenh = " grant "+grt2+" on "+nameTable+" to "+gr_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel3.getText().equals("")==false){
                lenh = " grant "+grt3+" on "+nameTable+" to "+gr_name;
                rs = stmt.executeUpdate(lenh);
            }
            if(jLabel4.getText().equals("")==false){
                lenh = " grant "+grt4+" on "+nameTable+" to "+gr_name;
                rs = stmt.executeUpdate(lenh);
            }
            
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Gán quyền cho role thành công!");
                
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GanQuyenChoNhomActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // sự kiện lấy dữ liệu từ combobox được chọn
        if(evt.getStateChange()== ItemEvent.SELECTED)
            jLabel8.setText(jComboBox2.getSelectedItem().toString());
        else
            jLabel8.setText("");
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void ButtonThuHoiNhomQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonThuHoiNhomQuyenActionPerformed
        // thu hồi role của user
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Tạo kết nối đến server
            Connection con = DriverManager.getConnection(dbURL, username, password);
//                    "jdbc:oracle:thin:@localhost:1521:orcl", "sys as sysdba", "Matkhau123");
            int vt= jTable1.getSelectedRow();
            String user_name = jTable1.getValueAt(vt,0).toString();
            String tenGr = jLabel8.getText();
            Statement stmt = con.createStatement();
            int rs = stmt.executeUpdate("revoke "+tenGr+" from "+user_name);
            if(rs != 1)
                JOptionPane.showMessageDialog(this, "Thu hồi nhóm quyền của user thành công!");
                
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonThuHoiNhomQuyenActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Grant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCapQuyen;
    private javax.swing.JButton ButtonCreateGroupGrant;
    private javax.swing.JButton ButtonDeleteGroupGrant;
    private javax.swing.JButton ButtonGroupGrantUser;
    private javax.swing.JButton ButtonLoadGr;
    private javax.swing.JButton ButtonReturnMain;
    private javax.swing.JButton ButtonThuHoiNhomQuyen;
    private javax.swing.JButton ButtonThuHoiQuyen;
    private javax.swing.JButton GanQuyenChoNhom;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
